-- 국제크레인 고객후기 테이블 (Supabase SQL Editor에서 1회 실행)
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 20),
  area text,
  work_type text,
  rating integer not null check (rating between 1 and 5),
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

drop policy if exists "public can read reviews" on public.reviews;
drop policy if exists "public can insert reviews" on public.reviews;

create policy "public can read reviews"
on public.reviews for select
to anon, authenticated
using (true);

create policy "public can insert reviews"
on public.reviews for insert
to anon, authenticated
with check (true);

revoke update, delete on table public.reviews from anon, authenticated;
